### ISSUE TITLE
[FEATURE] Use dynamic libraries for plugins

### ISSUE THREAD

**Issue by infinity-plus** [ProjectBlackPearl/project_black_pearl#42]
**Is your feature request related to a problem? Please describe.**<br>
No, my issue is not related to a problem. However, it can be a potential measure against problems in future,

**Describe the solution you'd like**<br>
Currently, our Rust project uses binary plugins to extend its functionality. While this approach has worked well for us so far, it has some limitations. Binary plugins require users to download and install pre-compiled binaries that are specific to their system architecture and operating system. This can be difficult and error-prone, especially for users who are not familiar with compiling and installing software.

Another issue with binary plugins is that they can have performance implications. Binary plugins are statically linked to the application, which means they are loaded into memory at startup and cannot be unloaded until the application exits. This can lead to increased memory usage and slower startup times for the application. Dynamic libraries, on the other hand, are loaded and unloaded at runtime, which can help reduce memory usage and improve startup times.

In addition, binary plugins can pose security risks. Because they are compiled code, it can be difficult to verify their source and ensure they are not malicious. Dynamic libraries, on the other hand, can be loaded with stricter security measures, such as signed libraries, that help ensure the code is trusted and safe to use.

To address these issues, I propose that we switch to using dynamic libraries as plugins. Dynamic libraries can be loaded and unloaded at runtime, which means users can add and remove plugins without needing to download or compile any code. Dynamic libraries can also be updated more easily, since users can simply replace the library file.

**Additional context**<br>
To implement this, we would need to:

- Update our plugin system to support dynamic libraries. This would involve changing our plugin interface to use dynamic linking instead of static linking.

- Provide documentation and examples for users on how to create dynamic library plugins.

- Update our build process to include support for building dynamic library plugins.

I believe this change would make our project more user-friendly, easier to extend, and potentially more secure. Please let me know your thoughts on this proposal.

**Comment by infinity-plus** [comment]
An example of interface:
```rust
#[derive(Debug)]
pub struct Link {
    pub label: String,
    pub url: String,
}

#[derive(Debug)]
pub struct Game {
    pub title: String,
    pub links: Vec<Link>,
}
pub trait SearchService {
    fn search(&self, query: String) -> Result<Vec<Game>, String>;
}
```

**Comment by infinity-plus** [comment]
We do need to implement a versioning system though.

**Comment by infinity-plus** [comment]
Okay, implemented a versioning system:
```rust
#[derive(Debug)]
pub struct Link {
    pub label: String,
    pub url: String,
}

#[derive(Debug)]
pub struct Game {
    pub title: String,
    pub links: Vec<Link>,
}
pub trait PluginInterface {
    //  Add a method to get the schema version of the interface.
    fn version(&self) -> &'static str {
        "0.1.0"
    }

    //  Add a method to get the name of the plugin.
    fn name(&self) -> &'static str;

    //  Add a method to get the author of the plugin.
    fn author(&self) -> &'static str;

    // Add a method to get source of the plugin.
    fn source(&self) -> &'static str;

    //  Add a search method to the interface.
    fn search(&self, query: String) -> Result<Vec<Game>, String>;
}

impl dyn PluginInterface {
    pub fn check_version(&self, version: &str) -> bool {
        version == self.version()
    }
}
```

**Comment by Brisolo32** [comment]
When using the `install_plugin` function it doesn't install at all. It creates the folder but no file to be seen, and no logs also on the CMD, but there is a error message at the Console

```
Unhandled Promise Rejection: Failed to copy plugin: No such file or directory (os error 2)
```

**Comment by infinity-plus** [comment]
Yeah my bad. We were creating a folder called "plugin" and were searching for a folder called "plugins". It is fixed now. Pushed to the linked branch.

We will be using "plugins" folder name.
