### ISSUE TITLE
[FEATURE] Add support for flags and CLI arguments

### ISSUE THREAD

**Issue by Brisolo32** [ProjectBlackPearl/project_black_pearl#48]
**Is your feature request related to a problem?**<br>
My feature is related to a problem, it is described on the next item.

**What feature would you like to be added?**<br>
- Adding another input box for CLI arguments/flags

**Additional Information:**<br>
At present, Linux users face limitations when it comes to running specific games, particularly those designed for Windows, due to the lack of compatibility with the Wine tool. To address this issue, I suggest introducing an additional feature that allows users to input both the game's path and relevant flags.

By implementing this solution, running games through Wine would become feasible. The first input box would be designated for specifying the path to Wine, typically located at /usr/bin/wine. The second input box would enable users to provide the path to the game itself, facilitating seamless execution.

**Comment by TerrenceTingleberry** [comment]
> This can be achieved by saving game path + flags in a bash script and then adding it to PBP. Still, interesting, let's discuss.

While I had this same thought and it is definitely possible, it's definitely less than optimal and could potentially lead to some other pains down the road as the app grows and plugins become more complex. So, I definitely agree this should be discussed further and implemented if possible.

**Comment by infinity-plus** [comment]
> > This can be achieved by saving game path + flags in a bash script and then adding it to PBP. Still, interesting, let's discuss.
> 
> While I had this same thought and it is definitely possible, it's definitely less than optimal and could potentially lead to some other pains down the road as the app grows and plugins become more complex. So, I definitely agree this should be discussed further and implemented if possible.

I don't see how it's related to plugins in any way. Can you please elaborate on "pains down the road"?

**Comment by Brisolo32** [comment]
> This can be achieved by saving game path + flags in a bash script and then adding it to PBP. Still, interesting, let's discuss.

I have already tried saving it to a bash script and it doesn't work, both on linux and windows require a command before (Linux: bash interpreter like `bash` and on windows the `start` command)

Something that detects when the file terminates with .sh or .bat might work, but in general it's best to have 2 input boxes, like steam
